export const adminActionType = {
  FETCH_USER_DELETE_REQUEST: "FETCH_USER_DELETE_REQUEST",
  FETCH_USER_DELETE_SUCCESS: "FETCH_USER_DELETE_SUCCESS",
  FETCH_USER_DELETE_FAILURE: "FETCH_USER_DELETE_FAILURE",

  //update actionType
  USER_UPDATE_REQUEST: "USER_UPDATE_REQUEST",
  USER_UPDATE_SUCCESS: "USER_UPDATE_SUCCESS",
  USER_UPDATE_FAILURE: "USER_UPDATE_FAILURE",
};
export const USER_RESET_SUCCESS= "USER_RESET_SUCCESS"
