const mcqType = {
  POST_MCQ_REQUEST: "POST_MCQ_REQUEST",
  POST_MCQ_SUCCESS: "POST_MCQ_SUCCESS",
  POST_MCQ_FAIL: "POST_MCQ_FAIL",

  GET_MCQ_REQUEST: "GET_MCQ_REQUEST",
  GET_MCQ_SUCCESS: "GET_MCQ_SUCCESS",
  GET_MCQ_FAIL: "GET_MCQ_FAIL",
};

export default mcqType;
